Repository CycloneDX/cyclonedx-webpack-plugin, pull requests merged in 2025-01, with the labels that each got.

#1331 feat: tools as components
  HISTORY.md
  package.json
  src/plugin.ts
  tests/integration/__snapshots__/index.test.js.snap
  tests/integration/index.test.js
Labels: enhancement, breaking-change, schema 1.5

#1333 feat!: emit defaults to CycloneDX1.6
  HISTORY.md
  README.md
  src/plugin.ts
  tests/integration/__snapshots__/index.test.js.snap
Labels: enhancement, breaking-change, schema 1.6

#1354 feat: emit webpack as `metadata.tools`
  HISTORY.md
  src/plugin.ts
  tests/integration/__snapshots__/index.test.js.snap
  tests/integration/index.test.js
Labels: enhancement

#1355 fix: prevent multiple, duplicate build-system entries
  src/plugin.ts
Labels: bug
